package main

import (
	"net/http"
	"net/url"
)

type bangHandler func(response http.ResponseWriter, request *http.Request, query string)

var bangHandlers map[string]bangHandler = map[string]bangHandler{
	"": func(response http.ResponseWriter, request *http.Request, query string) {
		http.Redirect(response, request, "https://kagi.com/search?q="+url.QueryEscape(query), http.StatusFound)
	},
	"!go": func(response http.ResponseWriter, request *http.Request, query string) {
		var isGoStandardPackage bool
		_, isGoStandardPackage = goStandardPackages[query]
		if isGoStandardPackage {
			http.Redirect(response, request, "https://pkg.go.dev/"+url.QueryEscape(query), http.StatusFound)
			return
		}
		http.Redirect(response, request, "https://pkg.go.dev/search?utm_source=godoc&q="+url.QueryEscape(query), http.StatusFound)
	},
}

var goStandardPackages map[string]struct{} = map[string]struct{}{
	"archive/tar":          struct{}{},
	"archive/zip":          struct{}{},
	"bufio":                struct{}{},
	"builtin":              struct{}{},
	"bytes":                struct{}{},
	"cmp":                  struct{}{},
	"compress/bzip2":       struct{}{},
	"compress/flate":       struct{}{},
	"compress/gzip":        struct{}{},
	"compress/lzw":         struct{}{},
	"compress/zlib":        struct{}{},
	"container/heap":       struct{}{},
	"container/list":       struct{}{},
	"container/ring":       struct{}{},
	"context":              struct{}{},
	"crypto":               struct{}{},
	"crypto/aes":           struct{}{},
	"crypto/cipher":        struct{}{},
	"crypto/des":           struct{}{},
	"crypto/dsa":           struct{}{},
	"crypto/ecdh":          struct{}{},
	"crypto/ecdsa":         struct{}{},
	"crypto/ed25519":       struct{}{},
	"crypto/elliptic":      struct{}{},
	"crypto/fips140":       struct{}{},
	"crypto/hkdf":          struct{}{},
	"crypto/hmac":          struct{}{},
	"crypto/md5":           struct{}{},
	"crypto/mlkem":         struct{}{},
	"crypto/pbkdf2":        struct{}{},
	"crypto/rand":          struct{}{},
	"crypto/rc4":           struct{}{},
	"crypto/rsa":           struct{}{},
	"crypto/sha1":          struct{}{},
	"crypto/sha256":        struct{}{},
	"crypto/sha3":          struct{}{},
	"crypto/sha512":        struct{}{},
	"crypto/subtle":        struct{}{},
	"crypto/tls":           struct{}{},
	"crypto/x509":          struct{}{},
	"crypto/x509/pkix":     struct{}{},
	"database/sql":         struct{}{},
	"database/sql/driver":  struct{}{},
	"debug/buildinfo":      struct{}{},
	"debug/dwarf":          struct{}{},
	"debug/elf":            struct{}{},
	"debug/gosym":          struct{}{},
	"debug/macho":          struct{}{},
	"debug/pe":             struct{}{},
	"debug/plan9obj":       struct{}{},
	"embed":                struct{}{},
	"encoding":             struct{}{},
	"encoding/ascii85":     struct{}{},
	"encoding/asn1":        struct{}{},
	"encoding/base32":      struct{}{},
	"encoding/base64":      struct{}{},
	"encoding/binary":      struct{}{},
	"encoding/csv":         struct{}{},
	"encoding/gob":         struct{}{},
	"encoding/hex":         struct{}{},
	"encoding/json":        struct{}{},
	"encoding/pem":         struct{}{},
	"encoding/xml":         struct{}{},
	"errors":               struct{}{},
	"expvar":               struct{}{},
	"flag":                 struct{}{},
	"fmt":                  struct{}{},
	"go/ast":               struct{}{},
	"go/build":             struct{}{},
	"go/build/constraint":  struct{}{},
	"go/constant":          struct{}{},
	"go/doc":               struct{}{},
	"go/doc/comment":       struct{}{},
	"go/format":            struct{}{},
	"go/importer":          struct{}{},
	"go/parser":            struct{}{},
	"go/printer":           struct{}{},
	"go/scanner":           struct{}{},
	"go/token":             struct{}{},
	"go/types":             struct{}{},
	"go/version":           struct{}{},
	"hash":                 struct{}{},
	"hash/adler32":         struct{}{},
	"hash/crc32":           struct{}{},
	"hash/crc64":           struct{}{},
	"hash/fnv":             struct{}{},
	"hash/maphash":         struct{}{},
	"html":                 struct{}{},
	"html/template":        struct{}{},
	"image":                struct{}{},
	"image/color":          struct{}{},
	"image/color/palette":  struct{}{},
	"image/draw":           struct{}{},
	"image/gif":            struct{}{},
	"image/jpeg":           struct{}{},
	"image/png":            struct{}{},
	"index/suffixarray":    struct{}{},
	"io":                   struct{}{},
	"io/fs":                struct{}{},
	"io/ioutil":            struct{}{},
	"iter":                 struct{}{},
	"log":                  struct{}{},
	"log/slog":             struct{}{},
	"log/syslog":           struct{}{},
	"maps":                 struct{}{},
	"math":                 struct{}{},
	"math/big":             struct{}{},
	"math/bits":            struct{}{},
	"math/cmplx":           struct{}{},
	"math/rand":            struct{}{},
	"math/rand/v2":         struct{}{},
	"mime":                 struct{}{},
	"mime/multipart":       struct{}{},
	"mime/quotedprintable": struct{}{},
	"net":                  struct{}{},
	"net/http":             struct{}{},
	"net/http/cgi":         struct{}{},
	"net/http/cookiejar":   struct{}{},
	"net/http/fcgi":        struct{}{},
	"net/http/httptest":    struct{}{},
	"net/http/httptrace":   struct{}{},
	"net/http/httputil":    struct{}{},
	"net/http/pprof":       struct{}{},
	"net/mail":             struct{}{},
	"net/netip":            struct{}{},
	"net/rpc":              struct{}{},
	"net/rpc/jsonrpc":      struct{}{},
	"net/smtp":             struct{}{},
	"net/textproto":        struct{}{},
	"net/url":              struct{}{},
	"os":                   struct{}{},
	"os/exec":              struct{}{},
	"os/signal":            struct{}{},
	"os/user":              struct{}{},
	"path":                 struct{}{},
	"path/filepath":        struct{}{},
	"plugin":               struct{}{},
	"reflect":              struct{}{},
	"regexp":               struct{}{},
	"regexp/syntax":        struct{}{},
	"runtime":              struct{}{},
	"runtime/cgo":          struct{}{},
	"runtime/coverage":     struct{}{},
	"runtime/debug":        struct{}{},
	"runtime/metrics":      struct{}{},
	"runtime/pprof":        struct{}{},
	"runtime/race":         struct{}{},
	"runtime/trace":        struct{}{},
	"slices":               struct{}{},
	"sort":                 struct{}{},
	"strconv":              struct{}{},
	"strings":              struct{}{},
	"structs":              struct{}{},
	"sync":                 struct{}{},
	"sync/atomic":          struct{}{},
	"syscall":              struct{}{},
	"syscall/js":           struct{}{},
	"testing":              struct{}{},
	"testing/fstest":       struct{}{},
	"testing/iotest":       struct{}{},
	"testing/quick":        struct{}{},
	"testing/slogtest":     struct{}{},
	"text/scanner":         struct{}{},
	"text/tabwriter":       struct{}{},
	"text/template":        struct{}{},
	"text/template/parse":  struct{}{},
	"time":                 struct{}{},
	"time/tzdata":          struct{}{},
	"unicode":              struct{}{},
	"unicode/utf16":        struct{}{},
	"unicode/utf8":         struct{}{},
	"unique":               struct{}{},
	"unsafe":               struct{}{},
	"weak":                 struct{}{},
}
